README.md
leptos_i18n_macro/src/load_locales/interpolate.rs

Plurals want as a count `Fn() -> i64 + ..`, this is a little restrictive so now it accept `Fn() -> N + ..` with `N: Into<i64>`.
for exemple now this is accepted:
```
t!(i18n, click_count, count = || 42u8)
```

Support any type that implement `Into<i64>` for plurals

---

README.md
leptos_i18n_macro/src/load_locales/key.rs

Previously `fr-FR` would fail to be a valid locale as `-` can't be used as a Rust identifier, but `-` should also be allowed for any key (namespace, variable, component, ect..) so this PR replace `-` by `_` for *idents*, so `locales: ["fr-FR", "en"]` now produce
```rust
enum LocaleEnum {
fr_FR,
en
}
```
but the `LocaleVariant::as_str` function still return "fr-FR" and "en".

Fix: replace `-` by `_` for keys indent

---

README.md
examples/counter/Cargo.toml
examples/counter_plurals/Cargo.toml
examples/hello_world_actix/Cargo.toml
examples/hello_world_axum/Cargo.toml
examples/interpolation/Cargo.toml
examples/namespaces/Cargo.toml
leptos_i18n/Cargo.toml
leptos_i18n/src/lib.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs
leptos_i18n_macro/src/t_macro/mod.rs
tests/namespaces/Cargo.toml
tests/no_namespaces/Cargo.toml

It was before possible to supply twice the same value for interpolation without triggering any warning, this behavior is acceptable but not what you want.
This PR allow to create a warning when a key is supplied twice, this warning is emitted:
```bash
warning: use of deprecated method `i18n::builders::click_count_builder::<__count>::var_count`: variable `count` is already set
--> src\app.rs:36:42
|
36 |         <p>{t!(i18n, click_count, count, count)}</p>
|                                          ^^^^^
|
= note: `#[warn(deprecated)]` on by default
```
Usage of `#[deprecated]` does not output the best message but is the best solution provided by Rust to do this kind of thing for the moment.
See #30

Better errors when missing/duplicate interpolation keys

---

README.md
examples/counter/Cargo.toml
examples/counter/i18n.json
examples/counter_plurals/Cargo.toml
examples/counter_plurals/i18n.json
examples/hello_world_actix/Cargo.toml
examples/hello_world_actix/i18n.json
examples/hello_world_axum/Cargo.toml
examples/hello_world_axum/i18n.json
examples/interpolation/Cargo.toml
examples/interpolation/i18n.json
examples/namespaces/Cargo.toml
examples/namespaces/i18n.json
leptos_i18n/src/lib.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/cfg_file.rs
leptos_i18n_macro/src/load_locales/error.rs
leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/mod.rs
tests/namespaces/Cargo.toml
tests/namespaces/i18n.json
tests/no_namespaces/Cargo.toml
tests/no_namespaces/i18n.json

Configuration will now be situated in the cargo manifest instead of it's own file.
close #25

Move from `i18n.json` to `Cargo.toml` metadata

---

README.md
examples/counter/src/app.rs
examples/counter/src/i18n.rs
examples/counter/src/lib.rs
examples/counter_plurals/src/app.rs
examples/counter_plurals/src/i18n.rs
examples/counter_plurals/src/lib.rs
examples/hello_world_actix/src/app.rs
examples/hello_world_actix/src/i18n.rs
examples/hello_world_actix/src/lib.rs
examples/hello_world_axum/src/app.rs
examples/hello_world_axum/src/i18n.rs
examples/hello_world_axum/src/lib.rs
examples/interpolation/src/app.rs
examples/interpolation/src/i18n.rs
examples/interpolation/src/lib.rs
examples/namespaces/src/app.rs
examples/namespaces/src/i18n.rs
examples/namespaces/src/lib.rs
leptos_i18n/src/context.rs
leptos_i18n/src/lib.rs
leptos_i18n_macro/src/load_locales/mod.rs
tests/namespaces/src/app.rs
tests/namespaces/src/i18n.rs
tests/namespaces/src/lib.rs
tests/no_namespaces/src/app.rs
tests/no_namespaces/src/i18n.rs
tests/no_namespaces/src/lib.rs

Instead of expanding the macro elements in the current module, create module that contain all elements.
Also expose a wrapper for `provide_i18n_context` and `use_i18n_context` using the created `Locales` type.
And re-export the `t!` macro for commodity.
```rust
pub mod i18n {
pub struct I18nKeys {
// ...
}
pub enum LocaleEnum {
// ...
}
pub struct Locales;
pub fn provide_i18n_context();
pub fn use_i18n();
pub use leptos_i18n::t;
}
```

Expand locales in mod

---

README.md
leptos_i18n/Cargo.toml
leptos_i18n/src/lib.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/cfg_file.rs
leptos_i18n_macro/src/load_locales/error.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/key.rs
leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs
leptos_i18n_macro/src/load_locales/warning.rs

When anything goes wrong with the locales declaration the macro hard error and no code is generated, this can be frustrating when you have multiple locales and just want to iterate with one locale as the code won't compile.
To mitigate this issue this PR change the behavior for 2 cases: missing key and surplus key. The macro will now concider the default locale to be the source of truth, so if a key is in the default, but not in another locale, the other locale has a missing key, if a key is present in another locale but not in the default, the other locale has a surplus key.
When a missing key is encounter, it will default to the value given to the default locale, and a warning be emitted:
```bash
warning: use of deprecated function `i18n::warnings::w0`: Missing key "click_to_inc" in …
```

Generate warnings on missing keys instead of hard error

---

leptos_i18n/src/context.rs

Hello,
currently methods `I18nContext::get_keys` and `I18nContext::get_keys_untracked` have identical bodies and are always tracked by Leptos.\
I suppose it wasn't intended :)

fix(context): get_keys_untracked() is no longer tracked

---

README.md
leptos_i18n/src/context.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/locale_traits.rs
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/t_macro/mod.rs
leptos_i18n_macro/src/t_macro/parsed_input.rs

New utility macro that works like the `t!` macro but instead of taking the context as argument, take the desired locale:
```rust
use crate::i18n::{LocaleEnum, td};
td!(LocaleEnum::fr, hello_world)
```
This let you use a translation regardless of the current locale, enabling the use of multiple locales together:
```rust
use crate::i18n::{LocaleEnum, td};
view! {
<p>"In English:"</p>
<p>{td!(LocaleEnum::en, hello_world)}</p>
<p>"En Français:"</p>
<p>{td!(LocaleEnum::fr, hello_world)}</p>
}
```
This macro is re-exported in the `i18n` generated module, just like the `t!` macro.
This macro can be used outside leptos reactive system without problems, the return type is the same type of `I18nKeys.$key`, so if `hello_world` is a plain string `td!(LocaleEnum::fr, hello_world)` would return …

feat: New `td!` macro to directly use a locale

---

leptos_i18n_macro/src/load_locales/error.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs

With #48 missing keys don't hard errors anymore, but generate a warning and default to whatever value the default locale has for this key.
But maybe you don't want the warning and want this to be the intended behavior, there is the `suppress_key_warnings` feature for that, but it completly disable the warnings for all keys, and you would want to very specifically select the keys and the locales where the warnings are removed.
This PR adress this, you can now explicitly declare that the value for this key is defaulted, you can do that by giving the value `null` to the key in the json file of the locale:
`en.json`:
```json
{
"my_key": "whatever value"
}
```
`fr.json`:
```json
{
"my_key": null
}
```
(with `en`being the default locale)
This will give to `my_key` the value in `en` for the …

Explicit default

---

README.md
docs/design/expanded/load_locales.md
examples/counter/src/app.rs
examples/counter_plurals/src/app.rs
examples/hello_world_actix/src/app.rs
examples/hello_world_axum/src/app.rs
examples/interpolation/src/app.rs
examples/namespaces/src/app.rs
examples/subkeys/src/app.rs
examples/workspace/counter/src/app.rs
leptos_i18n/src/context.rs
leptos_i18n/src/fetch_locale.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/locale_traits.rs
leptos_i18n/src/server/actix.rs
leptos_i18n/src/server/axum.rs
leptos_i18n/src/server/mod.rs
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/t_macro/mod.rs
tests/namespaces/src/first_ns.rs
tests/namespaces/src/second_ns.rs
tests/no_namespaces/src/plurals.rs
tests/no_namespaces/src/subkeys.rs
tests/no_namespaces/src/tests.rs

For legacy reason and probably me not thinking enough there is this generated type that most of the crate is generic over: `Locales`.
It's just a type implementing a trait that declare the locale enum and the key struct, but now that things have moved around this type is not needed anymore, so this PR change those things:
- Remove the `Locales` trait
- Remove the generated `Locales` type
- Rename the `LocaleVariant` trait to `Locale`
- Rename the generated `LocaleEnum` enum to `Locale`
- Rename associated type `Variant` of trait `LocaleKeys` to `Locale`
- All functions generic over the deleted `Locales` trait are now generic over the `Locale` trait
This is technically a breaking change, but normally the only type/trait you should have used in any of those is `LocaleEnum`, so a quick …

Remove `Locales` type and `Locales` trait

---

README.md
docs/book/src/usage/03_t_macro.md
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/plural.rs
tests/json/src/plurals.rs
tests/yaml/src/plurals.rs

removed `Into<N>` for plurals and now default to `i32`

---

README.md
docs/book/src/01_introduction.md
docs/book/src/02_getting_started.md
docs/book/src/declare/01_key_value.md
docs/book/src/declare/02_interpolation.md
docs/book/src/declare/03_plurals.md
docs/book/src/declare/05_foreign_keys.md
docs/book/src/declare/06_mix_kinds.md
docs/book/src/setting_up/01_configuration.md
docs/book/src/setting_up/02_file_structure.md
docs/book/src/setting_up/03_namespaces.md
docs/book/src/usage/01_load.md
docs/book/src/usage/02_context.md
docs/book/src/usage/03_t_macro.md
docs/book/src/usage/04_td_macro.md
docs/book/src/usage/README.md
examples/counter/README.md
examples/counter_plurals/README.md
examples/csr/README.md
examples/hello_world_actix/README.md
examples/hello_world_axum/README.md
examples/interpolation/README.md
examples/namespaces/README.md
examples/subkeys/README.md
examples/workspace/README.md
examples/yaml/README.md
leptos_i18n/src/lib.rs
tests/namespaces/locales/en/second_namespace.json
tests/namespaces/locales/fr/second_namespace.json
tests/namespaces/src/second_ns.rs

I just used your crate for my own project an corrected some typos while reading the docs and book.
I'm not a native english speaker myself so my edit may not be 100% correct.
If you are using VS Code i suggest using the extension `streetsidesoftware.code-spell-checker` & `streetsidesoftware.code-spell-checker-french`.
with the setting `cSpell.language` you can also set multiple languages like `en,fr`.
I also added an extra test on top 😊

Fix typos in docs

---

README.md
docs/book/src/declare/05_foreign_keys.md
leptos_i18n_macro/src/load_locales/error.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs
leptos_i18n_macro/src/load_locales/plural.rs
tests/json/locales/en.json
tests/json/locales/fr.json
tests/json/src/foreign.rs

This PR add the possibility to supply args for foreign keys:
```json
{
"click_count": "You clicked {{ count }} times",
"clicked_twice": "{{ @click_count, count = 'two' }}"
}
```
```rust
load_locales!();
let clicked_twice = td!(Locale::en, clicked_twice);
assert_eq!(clicked_twice, "You clicked two times");
```
Arguments values must be string, delimited by either single quotes or double quotes.
Only arguments to variables can be supplied.

Supply args to foreign key

---

docs/book/src/SUMMARY.md
docs/book/src/usage/05_td_string_macro.md
leptos_i18n/Cargo.toml
leptos_i18n/src/display.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/locale_traits.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs
leptos_i18n_macro/src/load_locales/plural.rs
leptos_i18n_macro/src/t_macro/interpolate.rs
leptos_i18n_macro/src/t_macro/mod.rs
tests/common/src/lib.rs
tests/json/Cargo.toml
tests/json/src/plurals.rs
tests/json/src/subkeys.rs
tests/json/src/tests.rs

Enabling the `interpolate_display` feature generate code to implement `Display` for the builders.
You can now do
```rust
// click_count = "You clicked {{ count }} times"
assert_eq!(
td_string!(Locale::en, click_count, count = 10).to_string(),
"You clicked 10 times"
)
assert_eq!(
td_string!(Locale::en, click_count, count = "a lot of").to_string(),
"You clicked a lot of times"
)
```
Variables expect a value `T: Display`, Plural count expect the plural type and components expect.. brace for it ...
```rust
Fn(&mut fmt::Formatter, &dyn Fn(&mut fmt::Formatter) -> fmt::Result) -> fmt::Result
```
Type inference seams wanky with this one, so requires to manually type those unfortunately...
But basically you use it like this:
```rust
let b = |f: &mut core::fmt::Formatter,
children: &dyn Fn(&mut …
```

`td_string!` macro to create strings from translations

---

leptos_i18n_macro/src/t_macro/interpolate.rs
tests/json/locales/en.json
tests/json/locales/fr.json
tests/json/src/lib.rs
tests/json/src/subkeys.rs
tests/json/src/tests.rs

This PR add this syntax to `t!` and `td!` for components:
```rust
// key = "<b>{{ count }}</b>"
t!(i18n, key, <b> = <span />, count = 32);
```
This will render `<span>32</span>`.
You can set attributes, event handlers, props ect:
```rust
t!(i18n, key, <b> = <span attr:id="my_id" on:click=|_| { /* do stuff */} />, count = 0);
```
Basically `<name .../>` expand to `move |children| view! { <name ...>{move || children()}</name> }`

Direct component for interpolation

---

leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs

This make `Bloc(String, Bloc(String, Variable, String), String)` turn into `Bloc(String, Variable, String)` where strings are merged together even at different depth, this takes a bit more computation but can avoid some unecessary overhead at runtime.

Flatten blocs of parsed value

---

leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs

Previously the check for explicit default in the default locale was only done at depth 1, so it was still possible to put explicit defaults in subkeys for the default locale, which would cause the generation of bad code.
This also fix an edge case where you could have a foreign key to an explicit default in the default locale, entering an infinite loop as foreign key to a default would then resolve the default, entering an infinite loop and causing a rustc stack overflow.

Fix explicit default in default locale

---

README.md
leptos_i18n/Cargo.toml
leptos_i18n/src/fetch_locale.rs
leptos_i18n/src/lib.rs

Refactor `fetch_locale.rs` to use a `cfg_if` case flow to determine which implementation of `fetch_locale` to enable. This ensures only one implementation will ever be enabled.
Add a dependency on https://github.com/rust-lang/cfg-if to `leptos_i18n`.
Fixes: #82

fix: allow the 'ssr' and 'hydrate' features to be enabled together

---

leptos_i18n_macro/src/load_locales/error.rs
leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs

When interpolating `"{{ count }}"` it is first parsed as a normal variable, so when inside a plural it must be changed to another kind, this changed was only happening when ***merging*** the keys of the locales, but this merging don't happen when a single locale is used, causing a conflict for generics names in the generated code, this PR fix it.
closes #84.

fix: Plurals breaks when interpolating the count with a single locale

---

examples/counter/Cargo.toml
examples/counter_plurals/Cargo.toml
examples/csr/Cargo.toml
examples/hello_world_actix/Cargo.toml
examples/hello_world_actix/src/main.rs
examples/hello_world_axum/Cargo.toml
examples/hello_world_axum/src/fileserv.rs
examples/hello_world_axum/src/main.rs
examples/interpolation/Cargo.toml
examples/namespaces/Cargo.toml
examples/subkeys/Cargo.toml
examples/workspace/counter/Cargo.toml
examples/yaml/Cargo.toml
leptos_i18n/Cargo.toml
leptos_i18n/src/server/axum.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/t_macro/parsed_input.rs
tests/common/Cargo.toml
tests/json/Cargo.toml
tests/namespaces/Cargo.toml
tests/yaml/Cargo.toml

Leptos released it;s 0.6.x version a few days ago. Since I'm using this library as a dependency, I figured I'd take the liberty to update the leptos version depended on.

Update leptos dep to 0.6

---

README.md
docs/book/src/06_features.md
examples/hello_world_actix/Cargo.toml
examples/hello_world_axum/Cargo.toml
leptos_i18n/Cargo.toml
leptos_i18n/src/lib.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/tracking.rs
leptos_i18n_macro/src/load_locales/warning.rs

Add the use of the [path tracking api](https://github.com/rust-lang/rust/issues/99515) to help with cargo-leptos watch.
Before if you added `watch-additional-files = ["locales"]` in you manifest for watching the locales, the build system would not see the translations files as dependencies and would not rerun the `load_locales!` macro, now if you use nightly the macro will add those files as a dependencies and would rerun when then changes. Unfortunately this API is unstable (pretty bad API for the moment to be honnest) so it is only enabled with the "nightly" feature.

Track locales files in proc macro

---

docs/expanded_macros/t.md
docs/expanded_macros/td.md
leptos_i18n_macro/src/t_macro/interpolate.rs
tests/json/src/tests.rs

When a non-Copy arg is passed to the `t!` macro, the resulting closure is only FnOnce, even if the type of the arg impl `Clone`. 
Now clone the args making the function `Fn` and not just `FnOnce`.

Clone args for `t!`

---

README.md
docs/book/src/06_features.md
leptos_i18n/Cargo.toml
leptos_i18n/src/lib.rs
leptos_i18n_macro/Cargo.toml
leptos_i18n_macro/src/load_locales/cfg_file.rs
leptos_i18n_macro/src/load_locales/error.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/key.rs
leptos_i18n_macro/src/load_locales/locale.rs
leptos_i18n_macro/src/load_locales/mod.rs

By enabling the `show_keys_only` feature, only the key is displayed.
This can be helpfull to detect non translated string in the application.
close #99

Feature to replace translations by the key during dev

---

.github/workflows/ci.yml
leptos_i18n/Cargo.toml
leptos_i18n/src/context.rs
leptos_i18n/src/fetch_locale.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/server/actix.rs
leptos_i18n/src/server/axum.rs
leptos_i18n/src/server/mod.rs
leptos_i18n_macro/src/load_locales/locale.rs

Currently in csr, the chosen locale is always the default one, this is not the expected behavior.
This PR try to solves this issue.

Fix csr locale fetching

---

docs/expanded_macros/load_locales.md
leptos_i18n/src/lib.rs
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/declare_locales.rs
leptos_i18n_macro/src/load_locales/key.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/plural.rs

Add a macro that output the same code as `load_locales!` but don't need to access files, this is usefull to write tests and doctests.

private macro to declare locales in code

---

.github/workflows/ci.yml
docs/book/README.md
docs/book/src/SUMMARY.md
docs/book/src/usage/06_scoping.md
docs/expanded_macros/scope.md
examples/subkeys/src/app.rs
leptos_i18n/src/context.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/locale_traits.rs
leptos_i18n/src/scopes.rs
leptos_i18n_macro/src/lib.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/t_macro/mod.rs
leptos_i18n_macro/src/t_macro/parsed_input.rs
leptos_i18n_macro/src/utils/mod.rs
leptos_i18n_macro/src/utils/scoped.rs
tests/json/src/lib.rs
tests/json/src/scoped.rs
tests/namespaces/src/lib.rs
tests/namespaces/src/scoped.rs

This PR add a new scoping feature.
This new feature is meant to improve the DX by being able to scope a context, such that instead of
```rust
let i18n = use_i18n();
t!(i18n, namespace.subkeys.value);
```
You can now do
```rust
let ns = use_i18n_scoped!(namespace);
t!(ns, subkeys.value);
let sk = use_i18n_scoped!(namespace.subkey);
t!(sk, value);
```
And you can scope already defined context:
```rust
let i18n = use_i18n();
let sk = scope_i18n!(namespace.subkey);
t!(sk, value);
```
`use_i18n_scoped!(...)` expends to `scope_i18n!(use_i18n(), ...)`.
Everything is typestate, this feature should be zero cost.

Scoped contexts

---

docs/book/src/06_features.md
docs/book/src/usage/02_context.md
examples/ssr/axum_island/src/app.rs
leptos_i18n/Cargo.toml
leptos_i18n/src/context.rs
leptos_i18n/src/fetch_locale.rs
leptos_i18n_macro/src/load_locales/mod.rs

Give options for custom header accessor. It was already the case for cookies, now also for `Accept-Languages` header.

Header options

---

docs/book/src/usage/05_td_macro.md
docs/book/src/usage/06_td_string_macro.md
examples/ssr/axum_island/Cargo.toml
examples/ssr/hello_world_axum/Cargo.toml
examples/ssr/routing_ssr/Cargo.toml
leptos_i18n/src/macro_helpers/mod.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/t_macro/mod.rs

fixed t_string and updated docs

---

docs/book/src/usage/07_router.md
leptos_i18n/src/context.rs
leptos_i18n/src/fetch_locale.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/locale_traits.rs
leptos_i18n/src/macros.rs
leptos_i18n/src/routing.rs
leptos_i18n/src/scopes.rs
leptos_i18n_macro/src/load_locales/mod.rs

Allow the creation of localized route segments:
```rust
use leptos_i18n::i18n_path;
<Route path=i18n_path!(Locale, |locale| td_string!(locale, path_name)) view=.. />
```
If used outside a `I18nRoute`, it will not have any effect and only produce paths with the default locale.
close #164

Localize route paths

---

leptos_i18n/src/macro_helpers/interpol_args.rs
leptos_i18n_macro/src/load_locales/interpolate.rs

Due to the update of the `IntoView` trait, the bound `'static` is'nt part of it now and it was forgotten to add the bound during the update, causing errors for nested interpolated components. Fix #177

Add `'static` bound to interpolation generics

---

docs/book/src/SUMMARY.md
docs/book/src/usage/12_serverfn.md
leptos_i18n/src/context.rs
leptos_i18n/src/fetch_locale.rs
leptos_i18n/src/lib.rs
leptos_i18n/src/locale.rs

Add a function to resolve the user locale without a context. Does the same as `init_i18n_context().get_locale_untracked()` without creating unnecessary reactive values.
This is usefull to access a user locale in a server function, allowing:
```rust
#[server]
async fn get_locale() -> Result<Locale, ServerFnError> {
let locale = leptos_i18n::locale::resolve_locale();
Ok(locale)
}
```
close #187

Function to resolve the locale without a context

---

leptos_i18n_macro/src/load_locales/mod.rs

fixed the issue #195.
function `new` named now `__new_internal` to avoid collisions between translations named `new`  and the internal `new` function

Fixed issue #195: collision between function name

---

leptos_i18n_router/src/components.rs

Routing components need to be transparent. It also supports compiling with erase_components cfg flag.

fix: make routing component transparent

---

leptos_i18n_build/src/datakey.rs
leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_macro/src/load_locales/parsed_value.rs
leptos_i18n_parser/src/parse_locales/locale.rs
leptos_i18n_parser/src/parse_locales/mod.rs
leptos_i18n_parser/src/parse_locales/parsed_value.rs
leptos_i18n_parser/src/utils/mod.rs

When a key was missing the value was defaulted to the default locale, but the process was to simply clone the value.
This worked perfectly but introduce some duplicates strings, now the value is not cloned anymore but marked to be defaulted to another locale, this basically change
```rust
match locale {
Locale::en => "some string",
Locale::fr =>  "some string", // <- duplicated string
}
```
to 
```rust
match locale {
Locale::en | Locale::fr => "some string",
}
```

fixed string duplication for defaulted values

---

leptos_i18n_macro/src/load_locales/interpolate.rs
leptos_i18n_macro/src/load_locales/mod.rs
leptos_i18n_parser/src/parse_locales/locale.rs
leptos_i18n_parser/src/parse_locales/parsed_value.rs

allow recursive defaults and detect cycles, if a cycle is encountered use the default locale.
This has no effect for now as the only default is the default locale, but needed for some later features

Allow recursive defaults

---

leptos_i18n_macro/src/utils/mod.rs

EitherOf16 in leptos does not export a 'Q' variant.

Fix EitherOfWrapper letters mapping

---

docs/book/src/SUMMARY.md
docs/book/src/setting_up/01_configuration.md
docs/book/src/setting_up/04_inheritance.md
leptos_i18n_macro/src/load_locales/declare_locales.rs
leptos_i18n_parser/src/parse_locales/cfg_file.rs
leptos_i18n_parser/src/parse_locales/locale.rs
leptos_i18n_parser/src/parse_locales/mod.rs
leptos_i18n_parser/src/parse_locales/warning.rs

Allow to specify an inheritance for a locale:
```toml
[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "fr", "fr-CA"]
inherits = { fr-CA = "fr" }
```
This will default any missing keys in "fr-CA" to the value in "fr".
The "general" default for missing keys will still be the default locale, so if a key is missing in both "fr" and "fr-CA", the key will use the value in "en".
You can have recursive inheritances, this is allowed and works as expected:
```toml
[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "fr", "fr-CA", "fr-FR"]
inherits = { fr-CA = "fr-FR", fr-FR = "fr" }
```
> note: cyclic inheritance is also valid but I don't see the use, it's only supported because if we didn't detected cycles we could have an endless loop when resolving what default to use, …

Allow to configure locales inheritance
